### ISSUE TITLE
react-spinkit and loaders.css

### ISSUE THREAD

**Issue by PaulRBerg** [zeit/next-plugins#129]
Hi there!

First off, thank you for creating this framework and plugins, they're just amazing.

Trying to get this up and running with [react-spinkit](https://github.com/KyleAMathews/react-spinkit), however the `next-css` plugin doesn't seem to properly handle it. I've read on #85 that this should be solved by the module creator, but I just said to ask here first maybe there's a solution?

```
/Users/paulrberg/Documents/daghub/dev/consumer/node_modules/loaders.css/loaders.css:14
@-webkit-keyframes scale {
^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:152:10)
    at Module._compile (module.js:624:28)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/paulrberg/Documents/daghub/dev/consumer/node_modules/react-spinkit/dist/index.js:40:3)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
```

I'm using a custom Express server and this is my `next.config.js` file:

```
const withPlugins = require('next-compose-plugins')
const withCSS = require('@zeit/next-css')
const withSass = require('@zeit/next-sass')
const withImages = require('next-images')

const nextConfig = {
	useFileSystemPublicRoutes: false,
	webpack: (config) => {
		config.node = {
			fs: 'empty'
		}

		return config
	}
}

module.exports = withPlugins([
	withCSS,
	withSass,
	withImages
], nextConfig)
```

**Comment by PaulRBerg** [comment]
Nevermind, the solution was to set `process.env.REACT_SPINKIT_NO_STYLES` to true (in your environment variables).

**Comment by copas2** [comment]
Exactly how, please?

**Comment by PaulRBerg** [comment]
Using something like [dotenv](https://github.com/motdotla/dotenv).

**Comment by Malouda** [comment]
create a .env file in the root of your projects folder and put REACT_SPINKIT_NO_STYLES=false
