### ISSUE TITLE
next-typescript doesn't work with Next 6

### ISSUE THREAD

**Issue by delgermurun** [zeit/next-plugins#158]
After upgraded to version 6, TS plugin no longer working.

Here is error stack trace:
```
(node:9878) UnhandledPromiseRejectionWarning: Error: .plugins[0][1] must be an object, false, or undefined
    at assertPluginItem (...node_modules/@babel/core/lib/config/validation/option-a
/node_modules/@babel/core/lib/config/validation/option-assertions.js:157:15)
    at .../node_modules/@babel/core/lib/config/validation/option-assertions.js:134:14
    at Array.forEach (<anonymous>)
    at assertPluginList (/.../node_modules/@babel/core/lib/config/validation/option-assertions.js:133:9)
    at /.../node_modules/@babel/core/lib/config/validation/options.js:84:20
    at Array.forEach (<anonymous>)
    at validate (/.../node_modules/@babel/core/lib/config/validation/options.js:62:21)
    at /.../node_modules/@babel/core/lib/config/config-chain.js:141:36
    at cachedFunction (/.../node_modules/@babel/core/lib/config/caching.js:40:17)
    at init (/.../node_modules/@babel/core/lib/config/config-chain.js:122:12)
    at /.../node_modules/@babel/core/lib/config/config-chain.js:206:17
    at buildRootChain (/.../node_modules/@babel/core/lib/config/config-chain.js:85:20)
    at loadPrivatePartialConfig (/.../node_modules/@babel/core/lib/config/partial.js:41:53)
    at loadPartialConfig (/.../node_modules/@babel/core/lib/config/partial.js:66:16)
    at babelConfig (/.../node_modules/next/dist/server/build/webpack.js:88:57)
    at _callee2$ (/.../node_modules/next/dist/server/build/webpack.js:164:34)
    at tryCatch (/.../node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/.../node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/.../node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/.../node_modules/@babel/runtime/helpers/asyncToGenerator.js:12:30)
    at _next (/.../node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:9)
    at /.../node_modules/@babel/runtime/helpers/asyncToGenerator.js:34:7
(node:9878) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:9878) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by delgermurun** [comment]
@timneutkens thanks for quick response. Yes I have babelrc

this is it:
```
{
  "presets": ["env", "next/babel"],
  "plugins": [["transform-define", "./env-config.js"]]
}
```

Do you know what to change in it? Thanks.

**Comment by timneutkens** [comment]
Remove "env", and use the fix here: https://github.com/zeit/next.js/issues/4239

**Comment by delgermurun** [comment]
It works. Thanks.

**Comment by merrywhether** [comment]
Now that next is on babel 7, next-typescript can be changed to leverage the typescript babel preset.
