### ISSUE TITLE
 Error while using next-typescript plugin in a simple new project.

### ISSUE THREAD

**Issue by nabinked** [zeit/next-plugins#197]
Here is the error stack
```
 error  in ./pages/test/index.tsx

Module build failed: Error: include option is not provided to hot-self-accept-loader. Please upgrade all next-plugins to the latest version.
    at getRoute (D:\repos\work\accounting\node_modules\next\dist\build\loaders\hot-self-accept-loader.js:28:11)
    at Object.module.exports (D:\repos\work\accounting\node_modules\next\dist\build\loaders\hot-self-accept-loader.js:16:15)

 @ multi ./pages/test/index.tsx
```
here is the file content in pages/test/index.tsx
```jsx
import * as React from "react";

export default class Index extends React.Component<{}>{
    render() {
        return <h1>Hello world</h1>
    }
}
````

Package JSON
```json
 "dependencies": {
    "@zeit/next-sass": "^0.2.0",
    "@zeit/next-typescript": "^1.0.1",
    "next": "^6.0.4-canary.7",
    "node-sass": "^4.9.0",
    "react": "^16.4.1",
    "react-dom": "^16.4.1"
  },
  "devDependencies": {
    "@types/react": "^16.3.18"
  }
```

.babelrc
```
{
    "presets": [
      "next/babel",
      "@zeit/next-typescript/babel"
    ]
  }
```
next.config.js
```
const withTypescript = require('@zeit/next-typescript')
module.exports = withTypescript()
```

tsconfig.js
```
{
    "compileOnSave": false,
    "compilerOptions": {
        "target": "esnext",
        "module": "esnext",
        "jsx": "preserve",
        "allowJs": true,
        "moduleResolution": "node",
        "allowSyntheticDefaultImports": true,
        "noUnusedLocals": true,
        "noUnusedParameters": true,
        "removeComments": false,
        "preserveConstEnums": true,
        "sourceMap": true,
        "skipLibCheck": true,
        "noImplicitAny": true,
        "noImplicitReturns": true,
        "noImplicitThis": true,
        "strict": true,
        "baseUrl": ".",
        "lib": [
            "dom",
            "es2016"
        ]
    }
}
```

**Comment by nabinked** [comment]
Closing this. I think i may have not done `npm install`. No issues now. Sorry.

**Comment by timneutkens** [comment]
Created a pull request for next-typescript. This is related to that you're using the latest canary version, I hadn't updated next-typescript to reflect those changes.

**Comment by nabinked** [comment]
Awesome Thanks (y)
