### ISSUE TITLE
Missing dependencies on the @zeit/next-css@canary repo ?

### ISSUE THREAD

**Issue by Dylfaen** [zeit/next-plugins#230]
I'm trying to implement next-css with the latest features ( 0.2.1-canary.1) but it appears the `mini-css-extract-plugin` requires `webpack@^4.4.0`.

---

### Here's what i got

On`npm i --save @zeit/next-css@canary` :
`npm WARN mini-css-extract-plugin@0.4.1 requires a peer of webpack@^4.4.0 but none is installed. You must install peer dependencies yourself.`

On starting my Next.js project :
```
 /root/app/node_modules/mini-css-extract-plugin/dist/index.js:26
const { Template, util: { createHash } } = _webpack2.default;
TypeError: Cannot destructure property `createHash` of 'undefined' or 'null'.
at Object.<anonymous> (/root/app/node_modules/mini-css-extract-plugin/dist/index.js:26:44)
at Module._compile (module.js:641:30) at Object.Module._extensions..js (module.js:652:10)
at Module.load (module.js:560:32)
at tryModuleLoad (module.js:503:12)
at Function.Module._load (module.js:495:3)
at Module.require (module.js:585:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/root/app/node_modules/mini-css-extract-plugin/dist/cjs.js:3:18)
at Module._compile (module.js:641:30)
```

### My attempts to solve the issue so far

I tried manually adding webpack@^4.4.0 to the project but then more plugins require other versions of webpack :

```
npm WARN uglifyjs-webpack-plugin@1.1.6 requires a peer of webpack@^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-middleware@1.12.0 requires a peer of webpack@^1.0.0 || ^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
```

### More details
Here's my package.json at the end of this process :
```
{
  "name": "test-app",
  "version": "1.0.0",
  "description": "",
  "main": "src/index.js",
  "dependencies": {
    "@zeit/next-css": "^0.2.1-canary.1",
    "axios": "^0.18.0",
    "history": "^4.7.2",
    "isomorphic-unfetch": "^2.1.0",
    "moment": "^2.22.2",
    "next": "^6.1.1",
    "next-redux-wrapper": "^2.0.0",
    "react": "^16.4.1",
    "react-day-picker": "^7.1.10",
    "react-dom": "^16.4.1",
    "react-redux": "^5.0.7",
    "react-router-dom": "^4.3.1",
    "react-router-redux": "^5.0.0-alpha.9",
    "react-svg": "^4.1.8",
    "redux": "^4.0.0",
    "redux-devtools-extension": "^2.13.5",
    "redux-thunk": "^2.3.0",
    "webpack": "^4.16.3"
  },
  "devDependencies": {},
  "scripts": {
    "dev": "next"
  },
  "author": "",
  "license": "ISC"
}
```

Is it a problem with the way i use the plugin or does it come from the plugin itself, thus out of my reach ?
Any insights on what might go wrong ?

**Comment by timneutkens** [comment]
This is expected, Next.js currently doesn't use webpack 4. Once the new next@canary version comes out you'll be able to use it
