### ISSUE TITLE
Next CSS is erroring out on latest canary 0.2.1-canary.1

### ISSUE THREAD

**Issue by pantharshit00** [zeit/next-plugins#235]
I am constantly getting this error on lastest next CSS canary which I installed as I updated to next js 6.1.1-canary.4

Error log
```
 const { Template, util: { createHash } } = _webpack2.default;
[ui:dev ]                                            ^
[ui:dev ] TypeError: Cannot destructure property `createHash` of 'undefined' or 'null'.
[ui:dev ]     at Object.<anonymous> (C:\code\javascript-af-ts\node_modules\mini-css-extract-plugin\dist\index.js:26:44)
[ui:dev ]     at Module._compile (internal/modules/cjs/loader.js:702:30)
[ui:dev ]     at Module._extensions..js (internal/modules/cjs/loader.js:713:10)
[ui:dev ]     at Object.require.extensions.(anonymous function) [as .js] (C:\code\javascript-af-ts\node_modules\ts-node\src\index.ts:431:14)
[ui:dev ]     at Module.load (internal/modules/cjs/loader.js:612:32)
[ui:dev ]     at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
[ui:dev ]     at Function.Module._load (internal/modules/cjs/loader.js:543:3)
[ui:dev ]     at Module.require (internal/modules/cjs/loader.js:650:17)
[ui:dev ]     at require (internal/modules/cjs/helpers.js:20:18)
[ui:dev ]     at Object.<anonymous> (C:\code\javascript-af-ts\node_modules\mini-css-extract-plugin\dist\cjs.js:3:18)
[ui:dev ] [nodemon] app crashed - waiting for file changes before starting...
```

Might be a webpack dep issue or typescript since I am using it.

my next.config.js
```js
const withTypescript = require("@zeit/next-typescript");
const withFonts = require("next-fonts");
const withCss = require("@zeit/next-css");
const withPlugins = require("next-compose-plugins");

module.exports = withPlugins([withFonts, withCss, withTypescript]);
```

repository: https://github.com/javascript-af/javascript-af-ts

**Comment by timneutkens** [comment]
The reason you're seeing this is that somewhere in your app you installed webpack 3.

**Comment by pantharshit00** [comment]
@timneutkens 

Just a question I have tried installing this 4 times and each time I am getting webpack 3 in yarn lock and node_modules

```yaml
next@^6.1.1-canary.4:
  version "6.1.1"
  resolved "https://registry.yarnpkg.com/next/-/next-6.1.1.tgz#b86d6b773871cfeb189b926eb7089d12f291668e"
  dependencies:
    "@babel/core" "7.0.0-beta.42"
    "@babel/plugin-proposal-class-properties" "7.0.0-beta.42"
    "@babel/plugin-proposal-object-rest-spread" "7.0.0-beta.42"
    "@babel/plugin-syntax-dynamic-import" "7.0.0-beta.42"
    "@babel/plugin-transform-react-jsx-source" "7.0.0-beta.42"
    "@babel/plugin-transform-runtime" "7.0.0-beta.42"
    "@babel/preset-env" "7.0.0-beta.42"
    "@babel/preset-react" "7.0.0-beta.42"
    "@babel/runtime" "7.0.0-beta.42"
    "@babel/template" "7.0.0-beta.42"
    ansi-html "0.0.7"
    babel-core "7.0.0-bridge.0"
    babel-loader "8.0.0-beta.3"
    babel-plugin-react-require "3.0.0"
    babel-plugin-transform-react-remove-prop-types "0.4.13"
    case-sensitive-paths-webpack-plugin "2.1.1"
    cross-spawn "5.1.0"
    del "3.0.0"
    etag "1.8.1"
    event-source-polyfill "0.0.12"
    find-up "2.1.0"
    fresh "0.5.2"
    friendly-errors-webpack-plugin "1.6.1"
    glob "7.1.2"
    hoist-non-react-statics "2.5.0"
    htmlescape "1.1.1"
    http-errors "1.6.2"
    http-status "1.0.1"
    loader-utils "1.1.0"
    minimist "1.2.0"
    mkdirp-then "1.2.0"
    path-to-regexp "2.1.0"
    prop-types "15.6.0"
    prop-types-exact "1.1.1"
    react-lifecycles-compat "3.0.4"
    recursive-copy "2.0.6"
    resolve "1.5.0"
    send "0.16.1"
    source-map "0.5.7"
    strip-ansi "3.0.1"
    styled-jsx "2.2.6"
    touch "3.1.0"
    uglifyjs-webpack-plugin "1.1.6"
    unfetch "3.0.0"
    update-check "1.5.2"
    url "0.11.0"
    uuid "3.1.0"
    walk "2.3.9"
    webpack "3.10.0"
    webpack-dev-middleware "1.12.0"
    webpack-hot-middleware "2.19.1"
    webpack-sources "1.1.0"
    write-file-webpack-plugin "4.2.0"
```

I eventually solved this by adding webpack 4 to resolutions part in package.json but why its installing webapck 3 in the first place?

**Comment by timneutkens** [comment]
Looks like npm installs 6.1.1 as ^ resolves to stable 🤔

**Comment by pantharshit00** [comment]
I guess I may wait till the final release
