### ISSUE TITLE
Cannot import postcss in canary

### ISSUE THREAD

**Issue by allpwrfulroot** [zeit/next-plugins#256]
Trying to use a new third-party component that appears to use postcss:
```js
// styles.css
:root { 
   --primaryBrand: #FF9911;
...
```

Unfortunately, I can't get the file read no matter what I do with `@zeit/next-css@canary`:
 ```js
ERROR  Failed to compile with 1 errors                                                                          5:53:50 PM

 error  in ./node_modules/foobar/style.css

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/lib/index.js):
TypeError: Invalid PostCSS Plugin found: [0]
    at /Users/XXXXX/YYYYYYYYYYY/ZZZZZZZ/node_modules/postcss-load-plugins/lib/plugins.js:32:17
    at Array.forEach (<anonymous>)
    at plugins (/Users/XXXXX/YYYYYYYYYYY/ZZZZZZZ/node_modules/postcss-load-plugins/lib/plugins.js:21:15)
    at /Users/XXXXX/YYYYYYYYYYY/ZZZZZZZ/node_modules/postcss-load-config/index.js:64:18
    at <anonymous>
    at runLoaders (/Users/XXXXX/YYYYYYYYYYY/ZZZZZZZ/node_modules/webpack/lib/NormalModule.js:286:20)
    at /Users/XXXXX/YYYYYYYYYYY/ZZZZZZZ/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /Users/XXXXX/YYYYYYYYYYY/ZZZZZZZ/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/Users/XXXXX/YYYYYYYYYYY/ZZZZZZZ/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Promise.resolve.then.then.catch (/Users/XXXXX/YYYYYYYYYYY/ZZZZZZZ/node_modules/postcss-loader/lib/index.js:189:71)
    at <anonymous>

 @ ./node_modules/foobar/Component.js 18:0-41
...

/Users/XXXXX/YYYYYYYYYYY/ZZZZZZZ/node_modules/foobar/style.css:1
(function (exports, require, module, __filename, __dirname) { :root {
                                                              ^

SyntaxError: Unexpected token :
    at createScript (vm.js:80:10)
...
```

Been trying every workaround and next.config.js suggestion I can find, along with variations of postcss.config.js, but so far no luck

======
Updates: 
Tried rolling back to 6.1.0 and looking at older issues / StackOverflow, no luck. So I'm clearly misunderstanding something fundamental.

Tried more work with canary and managed to get a cleaner error:
```js
  ERROR  Failed to compile with 1 errors                                                                          7:52:22 PM

 error  in ./node_modules/foobar/style.css

Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
> :root {
...
```

**Comment by allpwrfulroot** [comment]
Abandoning this third-party component, and since the issue doesn't seem to be with canary, I'm closing this
