### ISSUE TITLE
Receiving error related to mini-css-extract-plugin regardless of updated deps

### ISSUE THREAD

**Issue by kylemh** [zeit/next-plugins#275]
**Using (locally, not merged)**
next@7.0.0
@zeit/next-css@1.0.1

**Error**
```/Users/kyleholmberg/PersonalProjects/front-end/node_modules/mini-css-extract-plugin/dist/index.js:20
  util: { createHash }
          ^

TypeError: Cannot destructure property `createHash` of 'undefined' or 'null'.
    at Object.<anonymous> (/Users/kyleholmberg/PersonalProjects/front-end/node_modules/mini-css-extract-plugin/dist/index.js:21:5)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/kyleholmberg/PersonalProjects/front-end/node_modules/mini-css-extract-plugin/dist/cjs.js:3:18)
    at Module._compile (module.js:652:30)
```

**Repo**
https://github.com/OperationCode/front-end

**Comment by kylemh** [comment]
Really having trouble finding the error here... I've taken the with-next-css example down locally and am reproducing my entire config step-by-step with no issues. 😞

**Comment by kylemh** [comment]
🤔 It's because Storybook installs Webpack 3.

Will try to update Storybook or figure out resolution

**Comment by laurianek** [comment]
@kylemh Did you manage to find a solution for this?

**Comment by kylemh** [comment]
@laurianek I ended putting webpack@latest into my devDeps. Everything seems to work again for the most part. 

I do want to point out, I'm having issues with Next-CSS and CSS modules, and I am concerned that the issue is somehow related to this workaround, given a widely touted workaround for THAT issue wont work for me. [See here for more info](https://spectrum.chat/thread/2183fc55-236d-42cb-92b9-3ab10acc6303?m=MTUzODYyODEwMDQ4Ng==). This could be unrelated, so definitely give adding webpack to devDeps a shot.
