### ISSUE TITLE
TypeError: Cannot destructure property `createHash` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by fshaikh** [zeit/next-plugins#280]
Nextjs Version: 6.1.1
next-css Version: 1.0.1

Importing css file as : 
```
import '@reversecurrent/formrenderer/FormRenderer.css';
```
next.config.js:
```
const withCSS = require('@zeit/next-css')
module.exports = withCSS()
```

When running next build, following error is shown:
```
TypeError: Cannot destructure property `createHash` of 'undefined' or 'null'.
    at Object.<anonymous> (C:\Development\React\learnnextjs-demo\node_modules\mini-css-extract-plugin\dist\index.js:21:5)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Development\React\learnnextjs-demo\node_modules\mini-css-extract-plugin\dist\cjs.js:3:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
```

Any suggestions please to build the app?

**Comment by timneutkens** [comment]
You're using Next 6 together with the Next 7 version of next-css, you'll have to use an older version of next-css.
