### ISSUE TITLE
Plugins compatibility with next@6

### ISSUE THREAD

**Issue by standy** [zeit/next-plugins#283]
After update `next-typescript@1.1.0` to `next-typescript@1.1.1` got build error: 
```
Module build failed: Error: [BABEL] D:\dev\Next_Site\pages\_document.tsx: .overrides is not allowed in preset options
    at D:\dev\Next_Site\node_modules\@babel\core\lib\config\validation\options.js:64:13
    at Array.forEach (<anonymous>)
    at validate (D:\dev\Next_Site\node_modules\@babel\core\lib\config\validation\options.js:62:21)
    at D:\dev\Next_Site\node_modules\@babel\core\lib\config\full.js:242:36
    at cachedFunction (D:\dev\Next_Site\node_modules\@babel\core\lib\config\caching.js:40:17)
    at loadPresetDescriptor (D:\dev\Next_Site\node_modules\@babel\core\lib\config\full.js:234:45)
    at D:\dev\Next_Site\node_modules\@babel\core\lib\config\full.js:58:19
    at Array.map (<anonymous>)
    at recurseDescriptors (D:\dev\Next_Site\node_modules\@babel\core\lib\config\full.js:56:36)
    at recurseDescriptors (D:\dev\Next_Site\node_modules\@babel\core\lib\config\full.js:87:27)
    at loadFullConfig (D:\dev\Next_Site\node_modules\@babel\core\lib\config\full.js:103:6)
    at D:\dev\Next_Site\node_modules\@babel\core\lib\transform.js:26:33
    at process._tickCallback (internal/process/next_tick.js:61:11)

 @ multi ./pages/_document.tsx
```

Next@7 brings webpack@4 & babel@7, so should it be breaking change for plugins to next@6? This is breaking change to me.
My complain only about version number, plugin works great :+1:

**Comment by Jungwoo-An** [comment]
In general, possible incompatibility build is increase major version
