### ISSUE TITLE
next-css and React hooks api incompatibility

### ISSUE THREAD

**Issue by sfkiwi** [zeit/next-plugins#339]
**Actual Result:**
I'm using the new react hooks api. When I don't use next-css everything works fine in both dev and production builds and once deployed to lambdas. If I include next-css I get the following error from react that I [can only use hooks inside of a function body](https://reactjs.org/docs/error-decoder.html/?invariant=298). 

**Expected Result**
Should not be receiving this error as the hooks api is being used correctly

**Description**
I'm wondering if next-css is affecting the babel transpiling in some way. Here is the actual error output of the build in the now deployment environment.
`````
{ Invariant Violation: Minified React error #298; visit https://reactjs.org/docs/error-decoder.html?invariant=298 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at /var/task/.next/server/static/WpcaR9XCUJjSt~nUaR4JK/pages/index.js:30:965
    at g (/var/task/.next/server/static/WpcaR9XCUJjSt~nUaR4JK/pages/index.js:30:1068)
    at U (/var/task/.next/server/static/WpcaR9XCUJjSt~nUaR4JK/pages/index.js:30:4233)
    at z.useState (/var/task/.next/server/static/WpcaR9XCUJjSt~nUaR4JK/pages/index.js:30:6425)
    at L (/var/task/.next/server/static/WpcaR9XCUJjSt~nUaR4JK/pages/index.js:14:12199)
    at processChild (/var/task/node_modules/react-dom/cjs/react-dom-server.node.development.js:2790:14)
    at resolve (/var/task/node_modules/react-dom/cjs/react-dom-server.node.development.js:2714:5)
    at ReactDOMServerRenderer.render (/var/task/node_modules/react-dom/cjs/react-dom-server.node.development.js:3098:22)
    at ReactDOMServerRenderer.read (/var/
`````
I also notice that its running react-dom-server.node.development.js so wondering if somehow dev dependencies are getting mixed with production dependencies?

Here is the code that is generating the error (but only when next-css is included)
`````
import styled from 'styled-components'
import ProjectCard from './ProjectCard'
import { useState, useEffect } from 'react';

const speed = 0.4;

const ProjectsContainer = styled.section`
  width: 100%;
  min-height: 600px;

  
  display: flex;
  flex-direction: column;
  justify-content: flex-start;
  align-items: center;
  background-color: white;
  border-top: 1px solid #aaa;
  z-index:1;
`

const InnerContainer = styled.div`
  width: 80%;
  max-width: 1200px;
  padding: 100px;
  margin: 0 auto;

  display: flex;
  flex-direction: row;
  justify-content: space-evenly;
  align-items: center;

  @media only screen 
      and (min-device-width: 375px) 
      and (max-device-height: 812px)
      and (orientation : portrait) 
      and (-webkit-device-pixel-ratio: 3) {
    
    margin: -50px auto 0 auto;
    flex-direction: column;
    justify-content: flex-start;
    align-items: center;
    padding: 0;
  }
`

const Heading = styled.div.attrs({
  style: ({ opacity }) => ({
    opacity: opacity
  })
})`
  opacity: 0.0;
  margin-top: 50px;
`

const Translate = styled.div.attrs({
  style: ({translateY}) => ({    
    WebkitTransform: `translate3D(0px, ${Math.min(-50, translateY)}px, 0px)`,
      transform: `translate3D(0px, ${Math.min(-50, translateY)}px, 0px)`
  })})`
  width: 100%;
  height: 100%;


  transition: transform 100ms linear ;
`

const ProjectSection = ({projects}) => {

  const [scroll, setScroll] = useState(0);

  var canUseDOM = !!(
    (typeof window !== 'undefined' &&
      window.document && window.document.createElement)
  );

  if (canUseDOM) {

    useEffect(() => {

      let ticking = false;
      let last_known_scroll_position = window.scrollY;

      function handleScrollEvent(e) {
        last_known_scroll_position = window.scrollY;

        if (!ticking) {

          window.requestAnimationFrame(function () {
            setScroll(last_known_scroll_position);
            ticking = false;
          });

          ticking = true;

        }
      }

      window.addEventListener('scroll', handleScrollEvent);

      return () => {
        window.removeEventListener('scroll', handleScrollEvent);
      };
    });
  }

  return (
    <ProjectsContainer>
      <Heading opacity={Math.min(1.0, (scroll - 250)/600)}>
        <h1>Heading Text goes here</h1>
      </Heading>
      <Translate translateY={-270 + (scroll * speed)}>
        <InnerContainer>
          {projects.map(({image, title, description}, i) => (
            <ProjectCard key={i} image={image} title={title} description={description} />
          ))}
        </InnerContainer>
      </Translate>
    </ProjectsContainer>
  )
}

export default ProjectSection
`````

My next.config.js looks like:

`````
const { PHASE_PRODUCTION_SERVER } = process.env.NODE_ENV === 'development' ? {} : require('next-server/constants');

module.exports = (phase, { defaultConfig }) => {
  if (phase === PHASE_PRODUCTION_SERVER) {
    
    return {
      /* production only config */
    }
  }
  const withCSS = require('@zeit/next-css')
  return withCSS({})
}
`````

Package.json
`````
{
  "main": "server.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "dev": "PORT=4000 node server.js",
    "build": "next build",
    "start": "NODE_ENV=production node server.js"
  },
  "dependencies": {
    "@zeit/next-css": "^1.0.2-canary.2",
    "babel-plugin-styled-components": "^1.8.0",
    "express": "^4.15.2",
    "next": "^7.0.2",
    "normalize.css": "^8.0.1",
    "react": "^16.7.0-alpha.2",
    "react-dom": "^16.7.0-alpha.2",
    "styled-components": "^4.1.1"
  },
  "devDependencies": {}
`````

**Comment by sfkiwi** [comment]
Fixed in https://github.com/zeit/next.js/pull/5828
