### ISSUE TITLE
The default export is not a React Component in page: "/"

### ISSUE THREAD

**Issue by andyhe886** [zeit/next-plugins#346]
Hi, i am trying to migrate my react app CSR to SSR with next js, so far i have been playing around and i am still trying to figure out what cause this problem. any help?

`Error: The default export is not a React Component in page: "/"
    at _callee3$ (/Users/andyhe/Documents/react-kannabis/node_modules/next/dist/server/render.js:242:19)
    at tryCatch (/Users/andyhe/Documents/react-kannabis/node_modules/@babel/runtime-corejs2/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/andyhe/Documents/react-kannabis/node_modules/@babel/runtime-corejs2/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/andyhe/Documents/react-kannabis/node_modules/@babel/runtime-corejs2/node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (/Users/andyhe/Documents/react-kannabis/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:5:24)
    at _next (/Users/andyhe/Documents/react-kannabis/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:27:9)
    at <anonymous>`

**Comment by timneutkens** [comment]
Please try to follow the issue template so that we get enough context to help you. In general when creating issues on GitHub it's a good practice to provide *as much information as possible* instead of just "I get this error".

Also, questions should be posted on https://spectrum.chat/next-js as there are more people able to help there 🙏
