### ISSUE TITLE
next-mdx: Run Jest tests

### ISSUE THREAD

**Issue by mulholio** [zeit/next-plugins#388]
* I'm running into issues when using Jest to test components which import MDX files. I'm getting two variations on the error which both appear to be to do with parsing '##' in the MDX file (see below).
* I thought that `next-mdx` edited the babel config and that this would then be picked up by Jest. However, this doesn't seem to be working.
* I'm not gettng error with components which don't contain MDX files.

### Error 1

```
 FAIL  __tests__/pages/index.test.js
  ● Test suite failed to run

    /Users/jamesmulholland/proj/peoplegoal-site/components/index/feature_1.mdx:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){## Feature 1
                                                                                             ^

    SyntaxError: Invalid or unexpected token

      1 | import React from 'react';
      2 | import DemoForm from '../components/_system/DemoForm';
    > 3 | import Feature1 from '../components/index/feature_1.mdx';
        | ^
      4 | import Feature2 from '../components/index/feature_2.mdx';
      5 | import Feature3 from '../components/index/feature_3.mdx';
      6 | import { ToastConsumer } from '../context/toastContext';

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
      at Object.<anonymous> (pages/index.js:3:1)

```

### Error 2

```
 FAIL  __tests__/pages/index.test.js
  ● Test suite failed to run

    /Users/jamesmulholland/proj/peoplegoal-site/components/index/feature_1.mdx:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){## Feature 1
                                                                                             ^

    SyntaxError: Invalid or unexpected token

      12 |       <Feature1 />
      13 |       <Feature2 />
    > 14 |       <Feature3 />
         |                                        ^
      15 |     </div>
      16 |     <ToastConsumer>
      17 |       {showToast => (

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
      at Object.<anonymous> (pages/index.js:14:40)
```

## Configuration Details

```JavaScript
// next.config.js

const withCSS = require('@zeit/next-css');
const withBundleAnalyzer = require('@zeit/next-bundle-analyzer');
const withSourceMaps = require('@zeit/next-source-maps');
const withMDX = require('@zeit/next-mdx')({
  extension: /\.mdx?$/u,
});

module.exports = withSourceMaps(
  withMDX(
    withCSS(
      withBundleAnalyzer({
        // CSS moduels
        cssModules: true,
        cssLoaderOptions: {
          importLoaders: 1,
          localIdentName: '[local]___[hash:base64:5]',
        },
        // no MDX files allowed as pages
        pageExtensions: ['js', 'jsx'],
        // Now.sh severless deployment
        target: 'serverless',
        // bundle analyzer options
        analyzeServer: ['server', 'both'].includes(
          process.env.BUNDLE_ANALYZE
        ),
        analyzeBrowser: ['browser', 'both'].includes(
          process.env.BUNDLE_ANALYZE
        ),
        bundleAnalyzerConfig: {
          server: {
            analyzerMode: 'static',
            reportFilename: '../bundles/server.html',
          },
          browser: {
            analyzerMode: 'static',
            reportFilename: '../bundles/client.html',
          },
        },
      })
    )
  )
);
```

```
// .babelrc

{
  "env": {
    "development": {
      "presets": ["next/babel"]
    },
    "production": {
      "presets": ["next/babel"]
    },
    "test": {
      "presets": [
        ["next/babel", { "preset-env": { "modules": "commonjs" } }]
      ]
    }
  }
}

```

```
// package.json

{
  "name": "create-next-example-app",
  "scripts": {
    "dev": "next",
    "build": "next build && yarn css",
    "now-build": "node scripts/slack-webhook.js && yarn build",
    "start": "next start",
    "css": "tailwind build pages/App.css",
    "eslint": "eslint ./",
    "lint": "prettier-eslint --write --print-width 70 --tab-width 2 --trailing-comma es5 --bracket-spacing --semi --single-quote \"./!(node_modules)/**/*.{js,jsx}\"",
    "analyze": "BUNDLE_ANALYZE=both yarn build",
    "analyze-server": "BUNDLE_ANALYZE=server yarn build",
    "analyze-client": "BUNDLE_ANALYZE=browser yarn build",
    "test": "NODE_ENV=test jest",
    "test-watch": "yarn jest --watch",
    "lighthouse": "lighthouse https://peoplegoal.website --view --quiet --output-path ./lighthouse/lighthouse-report.html"
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "lint-staged": {
    "*.{js,jsx}": [
      "prettier-eslint --write --print-width 70 --tab-width 2 --trailing-comma es5 --bracket-spacing --semi --single-quote",
      "git add"
    ]
  },
  "dependencies": {
    "@mdx-js/mdx": "^0.16.6",
    "@segment/snippet": "^4.4.0",
    "@sentry/browser": "^4.5.0",
    "@zeit/next-bundle-analyzer": "^0.1.2",
    "@zeit/next-css": "^1.0.1",
    "@zeit/next-mdx": "^1.2.0",
    "@zeit/next-source-maps": "^0.0.3",
    "autoprefixer": "^9.4.4",
    "contentful": "^7.1.0",
    "dotenv": "^6.2.0",
    "lodash": "^4.17.11",
    "next": "^8.0.0-canary.6",
    "node-fetch": "^2.3.0",
    "nprogress": "^0.2.0",
    "react": "^16.8.0-alpha.0",
    "react-dom": "^16.8.0-alpha.0",
    "react-markdown": "^4.0.6",
    "react-syntax-highlighter": "^10.1.2",
    "tailwindcss": "^0.7.3"
  },
  "devDependencies": {
    "@babel/core": "^7.2.2",
    "@babel/preset-env": "^7.3.1",
    "@evermind/eslint-config-base": "^1.11.4",
    "babel-core": "^7.0.0-bridge.0",
    "babel-jest": "^23.6.0",
    "enzyme": "^3.8.0",
    "enzyme-adapter-react-16": "^1.7.1",
    "eslint": "^5.12.0",
    "eslint-plugin-babel": "^5.3.0",
    "eslint-plugin-react": "^7.12.3",
    "jest": "^23.6.0",
    "lighthouse": "^4.0.0",
    "stylelint": "^9.9.0",
    "stylelint-config-standard": "^18.2.0"
  }
}

```

```JavaScript

// jest.setup.js

import { configure } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';

configure({ adapter: new Adapter() });

```

```JavaScript

// jest.config.js

module.exports = {
  setupFiles: ['<rootDir>/jest.setup.js'],
  testPathIgnorePatterns: [
    '<rootDir>/.next/',
    '<rootDir>/node_modules/',
  ],
  testLocationInResults: true,
  testMatch: [
    '**/__tests__/**/*.js',
    '**/?(*.)+(spec|test).js?(x)',
    '!**/node_modules/**',
  ],
  coverageDirectory: 'coverage',
  moduleNameMapper: {
    "\\.(css)$": "<rootDir>/node_modules/jest-css-modules",
  },
};

```

**Comment by timneutkens** [comment]
MDX is a tranform/loader in itself, it doesn't use Babel. So you'll have to transform the mdx files to jsx yourself if you want to test them, however, why would you want to test static text 🤔

There's not really anything we can do about this in next-mdx, so I'm going to close the issue.

**Comment by Pushplaybang** [comment]
possibly provide some documentation on how to make it compatible, or exclude it from your tests?
