### ISSUE TITLE
Next 8 & next-typescript

### ISSUE THREAD

**Issue by k0ff33** [zeit/next-plugins#398]
Hi, I've just upgraded my project to Next 8 and wanted to try the new `target: 'serverless'` option but am failing to set it up with `next-typescript`.

I've tried to pass it to webpack as described in [docs](https://www.npmjs.com/package/@zeit/next-typescript#usage):
```
const withTypescript = require('@zeit/next-typescript')

module.exports = withTypescript({
  webpack(config, options) {
    config.target = 'serverless'
    return config
  },
})
```
but get:
```
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration[0].target should be one of these:
   "web" | "webworker" | "node" | "async-node" | "node-webkit" | "electron-main" | "electron-renderer" | function
   -> Environment to build for
   Details:
    * configuration[0].target should be one of these:
      "web" | "webworker" | "node" | "async-node" | "node-webkit" | "electron-main" | "electron-renderer"
    * configuration[0].target should be an instance of function
 - configuration[1].target should be one of these:
   "web" | "webworker" | "node" | "async-node" | "node-webkit" | "electron-main" | "electron-renderer" | function
   -> Environment to build for
   Details:
    * configuration[1].target should be one of these:
      "web" | "webworker" | "node" | "async-node" | "node-webkit" | "electron-main" | "electron-renderer"
    * configuration[1].target should be an instance of function
    at Object.webpack [as default] (/Users/kamilwojtczyk/Developer/awdis/code/awdis-admin/node_modules/webpack/lib/webpack.js:31:9)
    at HotReloader.start (/Users/kamilwojtczyk/Developer/awdis/code/awdis-admin/node_modules/next/dist/server/hot-reloader.js:187:48)
```

My guess is that `next-typescript` needs to be updated to support Next 8? I asked about it on [Spectrum](https://spectrum.chat/next-js/general/next-8-typescript~e08bb959-c5dc-4ea8-998e-a8867ecc6d9b).

**Comment by k0ff33** [comment]
I'm not sure why I haven't thought about the simplest solution:
```
const withTypescript = require('@zeit/next-typescript')

module.exports = withTypescript({
  target: 'serverless',
})
```
This works fine 👍.

**Comment by schabluk** [comment]
@k0ff33 which version of @zeit/next-typescript are you using?

**Comment by k0ff33** [comment]
I'm using v1.1.1.

Seems to work fine, however, throws a webpack warning when using `next build`:
```
yarn run v1.13.0
$ next build

✔ Client
  Compiled successfully in 11.16s

> Using external babel configuration
> Location: "/Users/kamilwojtczyk/Developer/awdis/code/awdis-admin/.babelrc"

✔ Client
  Compiled successfully in 11.16s

✔ Server
  Compiled successfully in 9.53s

> Emitted warnings from webpack
ModuleDependencyWarning: Critical dependency: the request of a dependency is an expression
    at Compilation.reportDependencyErrorsAndWarnings (/Users/kamilwojtczyk/Developer/awdis/code/awdis-admin/node_modules/webpack/lib/Compilation.js:1361:23)
    at Compilation.finish (/Users/kamilwojtczyk/Developer/awdis/code/awdis-admin/node_modules/webpack/lib/Compilation.js:1167:9)
    at hooks.make.callAsync.err (/Users/kamilwojtczyk/Developer/awdis/code/awdis-admin/node_modules/webpack/lib/Compiler.js:622:17)
    at _err0 (eval at create (/Users/kamilwojtczyk/Developer/awdis/code/awdis-admin/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:11:1)
    at Promise.all.then (/Users/kamilwojtczyk/Developer/awdis/code/awdis-admin/node_modules/webpack/lib/DynamicEntryPlugin.js:74:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at CommonJsRequireContextDependency.getWarnings (/Users/kamilwojtczyk/Developer/awdis/code/awdis-admin/node_modules/webpack/lib/dependencies/ContextDependency.js:40:18)
    at Compilation.reportDependencyErrorsAndWarnings (/Users/kamilwojtczyk/Developer/awdis/code/awdis-admin/node_modules/webpack/lib/Compilation.js:1356:24)
    at Compilation.finish (/Users/kamilwojtczyk/Developer/awdis/code/awdis-admin/node_modules/webpack/lib/Compilation.js:1167:9)
    at hooks.make.callAsync.err (/Users/kamilwojtczyk/Developer/awdis/code/awdis-admin/node_modules/webpack/lib/Compiler.js:622:17)
    at _err0 (eval at create (/Users/kamilwojtczyk/Developer/awdis/code/awdis-admin/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:11:1)
    at Promise.all.then (/Users/kamilwojtczyk/Developer/awdis/code/awdis-admin/node_modules/webpack/lib/DynamicEntryPlugin.js:74:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
 ┌ /
 ├ /_app
 ├ /_document
 └ /_error

(node:8649) [DEP0079] DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated
✨  Done in 22.58s
```
