### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by Chaysen** [zeit/next-plugins#492]
Hi,
I receive this error when I try to install or add the package to my repo.
Here my console output when I try to add the package.
```
yarn add @zeit/next-css                                 
yarn add v1.13.0
[1/4] 🔍  Resolving packages...
info There appears to be trouble with the npm registry (returned undefined). Retrying...
info There appears to be trouble with the npm registry (returned undefined). Retrying...
[2/4] 🚚  Fetching packages...
warning Pattern ["@zeit/next-css@^1.0.1"] is trying to unpack in the same destination "/Users/chaysenrathert/Library/Caches/Yarn/v4/npm-@zeit-next-css-1.0.1-4f784e841e7ca1b21b3468a902e2c1fa95a3e75c/node_modules/@zeit/next-css" as pattern ["@zeit/next-css@1.0.1","@zeit/next-css@1.0.1"]. This could result in non-deterministic behavior, skipping.
error An unexpected error occurred: "https://registry.yarnpkg.com/@zeit/next-css/-/next-css-1.0.1.tgz: Request failed \"503 Service Unavailable\"".
info If you think this is a bug, please open a bug report with the information provided in "/Users/chaysenrathert/Desktop/frontend/react-shopkit/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```
And the `yarn-error.log`:
```
Trace: 
  Error: https://registry.yarnpkg.com/@zeit/next-css/-/next-css-1.0.1.tgz: Request failed "503 Service Unavailable"
      at ResponseError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:702:66)
      at new ResponseError (/usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:808:124)
      at Request.<anonymous> (/usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:66325:16)
      at Request.emit (events.js:189:13)
      at Request.module.exports.Request.onRequestResponse (/usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:130274:10)
      at ClientRequest.emit (events.js:194:15)
      at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
      at TLSSocket.socketOnData (_http_client.js:442:20)
      at TLSSocket.emit (events.js:189:13)
```

**Comment by kachkaev** [comment]
Hi @Chaysen 👋 The error is to do with https://twitter.com/yarnpkg/status/1150713186905141248, which is unrelated to Next.js. It should be resolved by now.
