### ISSUE TITLE
next-preact: React version lower than the minimum required by Next.js.

### ISSUE THREAD

**Issue by sorleone** [zeit/next-plugins#497]
Why am I getting this error when using next-preact?

`Error: The version of React you are using is lower than the minimum required version needed for Next.js.`

https://github.com/zeit/next.js/blob/master/errors/invalid-react-version.md

**Comment by EliasTouil** [comment]
Getting the same error when I use the preact example from Next 2.0 and add 'new features' to my package.json

```
...
"dependencies": {
    "@zeit/next-preact": "0.1.0",
    "apollo-boost": "^0.4.3",
    "eslint": "^6.1.0",
    "eslint-config-synacor": "^3.0.4",
    "graphql": "^14.4.2",
    "if-env": "^1.0.4",
    "next": "latest",
    "preact": "^8.5.0",
    "preact-cli": "^2.2.1",
    "preact-compat": "^3.19.0",
    "preact-context": "^1.1.3",
    "preact-render-to-string": "^4.1.0",
    "preact-router": "^2.6.1",
    "react-apollo": "^2.5.8"
  },
```
  

### server.js
```const port = parseInt(process.env.PORT, 10) || 3000
const dev = process.env.NODE_ENV !== 'production'

require('@zeit/next-preact/alias')()

const { createServer } = require('http')
const { parse } = require('url')
const next = require('next')

const app = next({ dev })
const handle = app.getRequestHandler()

app.prepare().then(() => {
  createServer((req, res) => {
    const parsedUrl = parse(req.url, true)
    handle(req, res, parsedUrl)
  }).listen(port, err => {
    if (err) throw err
    console.log(`> Ready on http://localhost:${port}`)
  })
})
```
  

### next.config.js
```
const withPreact = require('@zeit/next-preact')

module.exports = withPreact()
```
  

### console output
```
yarn run v1.12.3
$ node server.js
/Users/eliastouil/Desktop/libofthings/alpha3/libofthings/using-preact-app/node_modules/next/dist/server/next-dev-server.js:1
(function (exports, require, module, __filename, __dirname) { "use strict";exports.__esModule=true;exports.default=void 0;var _nextServer=_interopRequireDefault(require("next-server/dist/server/next-server"));var _path=require("path");var _hotReloader=_interopRequireDefault(require("./hot-reloader"));var _router=require("next-server/dist/server/router");var _constants=require("next-server/constants");var _errorDebug=_interopRequireDefault(require("./error-debug"));var _amphtmlValidator=_interopRequireDefault(require("amphtml-validator"));var _index=require("../build/output/index");var Log=_interopRequireWildcard(require("../build/output/log"));var _verifyTypeScriptSetup=require("../lib/verifyTypeScriptSetup");var _watchpack=_interopRequireDefault(require("watchpack"));var _fs=_interopRequireDefault(require("fs"));var _utils=require("next-server/dist/lib/router/utils");var _react=_inte

Error: The version of React you are using is lower than the minimum required version needed for Next.js. Please upgrade "react" and "react-dom": "npm install --save react react-dom" https://err.sh/zeit/next.js/invalid-react-version
    at Object.<anonymous> (/Users/eliastouil/Desktop/libofthings/alpha3/libofthings/using-preact-app/node_modules/next/dist/server/next-dev-server.js:1:1485)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at module.exports.options (/Users/eliastouil/Desktop/libofthings/alpha3/libofthings/using-preact-app/node_modules/next/dist/server/next.js:2:55)
    at Object.<anonymous> (/Users/eliastouil/Desktop/libofthings/alpha3/libofthings/using-preact-app/server.js:10:13)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command
```

**Comment by dijs** [comment]
Got the same error, any ideas here? Can we disable it?

**Comment by timneutkens** [comment]
Updated the package readme: https://github.com/zeit/next-plugins/blob/master/packages/next-preact/readme.md
