### ISSUE TITLE
Spread operator doesn't work in next-css

### ISSUE THREAD

**Issue by pencilcheck** [zeit/next-plugins#60]
Next 5.0.1-canary.2
Node 8.1.3

```
yarn run v1.3.2
$ next build
/project/node_modules/@zeit/next-css/css-loader-config.js:31
      ...cssLoaderOptions
      ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/project/node_modules/@zeit/next-css/index.js:2:25)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Tried to remove existing next.config.js and replace it with vanila one like
```
const withCss = require('@zeit/next-css');

module.exports = withCss({
  webpack: (config, { buildId, dev, isServer, defaultLoaders }) => {

    return config;
  }
});

```

Still doesn't work

Btw, my babelrc

```
{
  "presets": [
    "next/babel",
    "stage-0",
    "flow",
  ],
  "plugins": [
    ["styled-components", { "ssr": true, "displayName": true, "preprocess": false, "minify": false, "transpileTemplateLiterals": false } ],
    "babel-plugin-root-import",
    "recharts",
    ["transform-define", "./env-config.js"],
    "transform-export-extensions",
    "transform-decorators-legacy",
    [
      "inline-import",
      {
        "extensions": [".css"]
      }
    ]
  ],
  "env": {
    "debug": true
  }
}
```

**Comment by pencilcheck** [comment]
Looks like 8.1.3 doesn't support spread operator on objects, upgraded to 9.0.0 and fixed it.

https://stackoverflow.com/questions/40066731/node-v6-failing-on-object-spread

**Comment by timneutkens** [comment]
Fixed the error either way 🙏
