### ISSUE TITLE
less use error

### ISSUE THREAD

**Issue by sq-zhou** [zeit/next-plugins#81]
When I use the module [@zeit/next-less](https://github.com/zeit/next-plugins/tree/master/packages/next-less), my configuration in next.config.js
```
const withLess = require('@zeit/next-less')
module.exports = withLess({
  cssModules: true
})
```
I use the example of [with-next-css](https://github.com/zeit/next.js/tree/canary/examples/with-next-css), and change style.css into style.less and even remove the file's content (had changed import '../style.css' in index.js to import  '../style.less' ), the error is 
```
Error in ../style.less
Module build failed: Error: Cannot find module 'less'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\work\wed\frontend-development\clone\with-next-css-app\node_modules\less-loader\dist\index.js:7:13)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\work\wed\frontend-development\clone\with-next-css-app\node_modules\less-loader\dist\cjs.js:3:18)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
```
Is this due to my next-less configuration error?

**Comment by timneutkens** [comment]
You forgot to install less. https://github.com/zeit/next-plugins/tree/master/packages/next-less#installation
