### ISSUE TITLE
SyntaxError: Invalid or unexpected token @

### ISSUE THREAD

**Issue by kushalsiddesh** [zeit/next-plugins#85]
Unable to resolve the build error, trying to work with ant design framework through modularized ant approach.

```
//.babelrc using babel-plugin-import
{
  "presets": ["next/babel"],
  "plugins": [
    [
      "import",
      {
        "libraryName": "antd",
        "style": "css"
      }
    ]
  ]
}
```

```
//.next.config.js

const withCSS = require("@zeit/next-css");
module.exports = withCSS();
```

Getting the following error :

```
/Users/crushy/dev/relive/node_modules/antd/lib/style/index.css:6
@font-face {
^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/crushy/dev/relive/node_modules/antd/lib/button/style/css.js:3:1)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.antd/lib/button/style/css (/Users/crushy/dev/relive/.next/dist/bundles/pages/external "antd/lib/button/style/css":1:1)
    at __webpack_require__ (/Users/crushy/dev/relive/.next/dist/bundles/pages/webpack/bootstrap 399d3c85f3fa45b2531f:21:1)
    at Object../components/Lane.js (/Users/crushy/dev/relive/.next/dist/bundles/pages/index.js:380:84)
    at __webpack_require__ (/Users/crushy/dev/relive/.next/dist/bundles/pages/webpack/bootstrap 399d3c85f3fa45b2531f:21:1)
    at Object../components/Vertical.js (/Users/crushy/dev/relive/.next/dist/bundles/pages/index.js:804:64)
/Users/crushy/dev/relive/node_modules/antd/lib/style/index.css:6
@font-face {
^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/crushy/dev/relive/node_modules/antd/lib/button/style/css.js:3:1)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.antd/lib/button/style/css (/Users/crushy/dev/relive/.next/dist/bundles/pages/external "antd/lib/button/style/css":1:1)
    at __webpack_require__ (/Users/crushy/dev/relive/.next/dist/bundles/pages/webpack/bootstrap 399d3c85f3fa45b2531f:21:1)
    at Object../components/Lane.js (/Users/crushy/dev/relive/.next/dist/bundles/pages/index.js:380:84)
    at __webpack_require__ (/Users/crushy/dev/relive/.next/dist/bundles/pages/webpack/bootstrap 399d3c85f3fa45b2531f:21:1)
    at Object../components/Vertical.js (/Users/crushy/dev/relive/.next/dist/bundles/pages/index.js:804:64)

```

**Comment by timneutkens** [comment]
> The error has been resolved by adding decorators to .babelrc but styles are not being applied to the components.

That's definitely not the solution, looks like the file is not being passed through the css transform, but through the JS transform (babel etc). Most likely antd turns the css import statements into `import "antd/example/example"` instead of `antd/example/example.css`

Someone from the antd team made the Next.js example, maybe you can file an issue on antd's repository, since there's not much we can do about it in next-css.

**Comment by xiaoxiaojx** [comment]
if some packages are still import files such as CSS
Use this package to solve https://github.com/xiaoxiaojx/with-ssr-entry
https://github.com/vercel/next.js/discussions/13828
